// packages/preact/src/index.tsx
import "monza-editor/style.css";
import { initialize, styles, type RenderOptions } from "monza-editor";
import type { JSX } from "preact";
import { useEffect, useRef } from "preact/hooks";

interface Props extends Omit<RenderOptions, "highlight"> {
  className?: string;
  id?: string;
  onHighlight: RenderOptions["highlight"];
}

export const Editor = ({
  className,
  id,
  onHighlight,
  ...rest
}: Props): JSX.Element => {
  const textarea = useRef<HTMLTextAreaElement>(null);
  const pre = useRef<HTMLPreElement>(null);
  const code = useRef<HTMLElement>(null);

  useEffect(() => {
    if (textarea.current && pre.current && code.current) {
      initialize({
        ...rest,
        code: code.current,
        highlight: onHighlight,
        pre: pre.current,
        textarea: textarea.current,
      });
    }
  }, []);

  return (
    <div className={`${styles.main} ${className}`} id={id}>
      <textarea class={styles.textarea} ref={textarea} />
      <pre class={styles.pre} ref={pre}>
        <code class={styles.code} ref={code} />
      </pre>
    </div>
  );
};

// packages/solid/src/index.tsx
import "monza-editor/style.css";
import { initialize, type RenderOptions, styles } from "monza-editor";
import { type JSX, onMount } from "solid-js";

interface Props extends Omit<RenderOptions, "highlight"> {
  class?: string;
  id?: string;
  onHighlight: RenderOptions["highlight"];
}

export const Editor = (props: Props): JSX.Element => {
  let textarea: HTMLTextAreaElement | undefined;
  let pre: HTMLPreElement | undefined;
  let code: HTMLElement | undefined;

  onMount(() => {
    if (textarea && pre && code) {
      initialize({
        ...props,
        code,
        highlight: props.onHighlight,
        pre,
        textarea,
      });
    }
  });

  return (
    <div class={`${styles.main} ${props.class}`} id={props.id}>
      <textarea class={styles.textarea} ref={textarea} />
      <pre class={styles.pre} ref={pre}>
        <code class={styles.code} ref={code} />
      </pre>
    </div>
  );
};
